### ISSUE TITLE
no reconnect after ping timeout

### ISSUE THREAD

**Issue by mouzaf** [monkeybird/autimaat#1]
After an IRC ping timeout the bot does not reconnect. Also, the software on the host keeps on running. Therefore systemd does not restart it. The bot never re-appears in the channel without manual intervention on the host. After an IRC ping timeout would be nice if the bot would either reconnect, or quit with failure (so systemd restarts it).

**Comment by mouzaf** [comment]
Reproducable like this:
- serverside: run ircd on port 6667, have iptables and have root
- clientside: start autimaat from prompt (profile.cfg points to server
  and a test channel), tail -f logfile
- connect with another irc client to the ircd, join test channel and
  check the bot is running normally
- serverside: block irc traffic to and from bot using iptables:
```
#!/bin/bash
iptables -I  INPUT 1 -p tcp -s xxx.xxx.xxx.xxx --dport 6667 -j DROP
iptables -I OUTPUT 1 -p tcp -d xxx.xxx.xxx.xxx --sport 6667 -j DROP
```
- wait for the ping timeout (default for ngircd is 20 seconds)

Result:
1. in ircd logs and/or in test channel: ping timeout visible
2. clientside: no messages in autimaat log, executable keeps on running

To clean up iptables rules:
```
#!/bin/bash
iptables -D  INPUT 1
iptables -D OUTPUT 1
```

**Comment by monkeybird** [comment]
Thanks!

**Comment by mouzaf** [comment]
I committed the first part of a fix. It fixes the issue, but I do not really understand why. Here I document my findings until now:
- If I make the bot not forking, the issue is not there. The non-forking bot exits on a I/O timeout, which is the desired behaviour.
- The forking bot does not get the I/O timeout. The behaviour 'feels like' SetDeadline() does not have any effect anymore in the child.
- Another bot written in golang does not have the issue. More importantly: it also does not have the issue after I make it self-forking on startup: https://github.com/nickvanw/ircx/tree/master/example (nonforking version).
- When forking, the parent creates a fd to the connection and uses exec.Cmd.ExtraFiles to pass it to the child.
- The fd is created via (*net.TCPConn).File(). The documentation of that function states:
>  File sets the underlying os.File to blocking mode and returns a copy. It is the caller's responsibility to close f when finished. Closing c does not affect f, and closing f does not affect c.
>The returned os.File's file descriptor is different from the connection's. Attempting to change properties of the original using this duplicate may or may not have the desired effect. 
- If I use 'the full bot' as a parameter to doFork(), instead of only using the fd and the forkargs, the forking bot behaves as desired. This is what I do in https://github.com/monkeybird/autimaat/commit/38d767e1de8d8d84b5b0a859498d67634d7fbdcd.

I still need to do some cleanup, especially app/proc/proc.go, as I did not yet remove doFork() and Wait() there. So the branch is not ready for merging yet. But it is now testable the fix works. Tip if you are going to test: use a small ConnectionTimeout for testing; just a bit larger then the PING timeout of the ircd.

@monkeybird @jteeuwen My proposal is to fix the issue like this, even though I don't understand why it works. Please let me know if you agree. Also if you have any thoughts on what is happening, or if you like to have more information I can supply, I am very happy to.
