### ISSUE TITLE
[plugins/url] Missing song titles in Spotify links.

### ISSUE THREAD

**Issue by monkeybird** [monkeybird/autimaat#15]
In the past few days, direct links to the Spotify site have shown incorrect title data.
E.g., the link `https://open.spotify.com/track/3wdLmIe8zlifCoOhb3N4nK` should return the title `Spotify Web Player - Last Run - Tokyo Rose`, where it returns `Spotify`.

Some examination of the webpage sources revealed that Spotify no longer recognized the user agent and returns an error page, instead of the song page being requested. This is the case for my current version of `Firefox`, as well as `wget` and the autimaat plugin (using Go's default HTTP client).

The solution to this, is to create a custom HTTP client and use it to perform the request with an explicitly defined UserAgent string.

**Comment by monkeybird** [comment]
@mouzaf This can be closed if the revisions are found to be working.

**Comment by monkeybird** [comment]
Commit 46626ccada7d6a2dac278628b1524c091287e05a adds additional fixes to address some issue introduced in commit 583b08723f123f663095ffcf7252195492e50777.

**Comment by mouzaf** [comment]
Seems like the expected title is not returned yet.

```
21:21   mouzaf : !versie
21:21  Jeeves  : znow, ik ben autimaat, versie 1.19. Mijn laatste revisie was op 21 June, 2017, 
                om 18:48 CEST. De laatste herstart was 2 uur geleden. Mijn broncode is te vinden 
                op: https://github.com/monkeybird/autimaat
21:21   mouzaf : https://open.spotify.com/track/3wdLmIe8zlifCoOhb3N4nK
21:21   Jeeves : De link van znow toont: Spotify
```

**Comment by mouzaf** [comment]
Spotify realised it should not check for user agents. It no longer requires a user agent to return the song title. https://github.com/monkeybird/autimaat/commit/db28571892c468500ef463cc3ecb6aa218dc80b4 reverts automaat to its old state. Closing this issue.
