### ISSUE TITLE
segfault on missing weather.cfg and url.cfg

### ISSUE THREAD

**Issue by mouzaf** [monkeybird/autimaat#2]
autimaat segfaults when weather.cfg and url.cfg are still missing. It would be nice if it quitted with some meaningfull message instead.

**Comment by monkeybird** [comment]
Interesting. I'm not seeing this behaviour on my system. Whenever one of these files does not exist, an error message is written to the current log file in `$BOT_PROFILE/logs/`.

The order in which the events occur is as follows:
```
* bot.go:48 - The bot loads all plugins.
* plugins/plugin.go:40 - The `Load` method is called on each plugin and the error it returns is checked.
  If the error is not nil, it is logged to the current external log file.
  For the `weather` and `url` plugins, this method attempts to read their respective, external configuration files.
* The bot will not quit or otherwise halt if one of the plugins yielded an error.
```

**Comment by mouzaf** [comment]
Sorry I forgot to mention that it segfaults when a command via IRC is given.
I just reproduced by moving the two mentioned files and saying !versie on IRC.

On the host:
'''
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x59b336]

goroutine 592 [running]:
panic(0x684800, 0xc420010080)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/monkeybird/autimaat/irc/cmd.(*Set).Dispatch(0x0, 0x805f80, 0xc4201b78a0, 0xc420051c20, 0x6f9b68)
        /home/mouz/work/src/github.com/monkeybird/autimaat/irc/cmd/set.go:46 +0x66
github.com/monkeybird/autimaat/plugins/weather.(*plugin).Dispatch(0xc42005f680, 0x805f80, 0xc4201b78a0, 0xc420051c20)
        /home/mouz/work/src/github.com/monkeybird/autimaat/plugins/weather/plugin.go:77 +0x4d
created by github.com/monkeybird/autimaat/plugins.Dispatch
        /home/mouz/work/src/github.com/monkeybird/autimaat/plugins/plugins.go:62 +0x86
'''

**Comment by monkeybird** [comment]
Ah, I see. Thanks. Fix is incoming.

**Comment by mouzaf** [comment]
Assuming issue was supposed to be closed on previous comment. Closing now.
