### ISSUE TITLE
watis does not find last entry

### ISSUE THREAD

**Issue by mouzaf** [monkeybird/autimaat#4]
The last entry in dictionary.txt is not found by !watis.

**Comment by monkeybird** [comment]
I just tried it with the current bot version on IRC:

```
17:09 <****> !watis zyprexa
17:09 <bot> ****: Olanzapine (merknamen Zyprexa of Zalasta) is een atypisch antipsychoticum. Artsen schrijven het voor bij psychose, manie,  onrust, schizofrenie en tics. Zie ook:  http://nl.wikipedia.org/wiki/Olanzapine
17:09 <bot> ****: Meer informatie van apotheek.nl: http://www.apotheek.nl/medicijnen/olanzapine
```

This assumes `zyprexa` is still the last entry as it is in my local copy of the dictionary. If not, can you give an example?

**Comment by mouzaf** [comment]
The last entry in dictionary.txt now reads
```
workaround
> Deze laatste dictionary entry is toegevoegd door mouz, als workaround, omdat de laatste entry niet gevonden wordt.
```

zyprexa's definition is just above that. The bot has been restarted several times since, so it certainly reread the new contents of dictionary.txt. Hope that answers your question.
